{% set name = "kvrocks" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6153af397deeb56af98e78cdbe093727dc6c62040467381c92eb7d1b694d1177

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - python
    - autoconf
    - make
    - cmake
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - openssl

test:
  commands:
    - kvrocks --version

about:
  home: https://kvrocks.apache.org
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  license_url: https://github.com/apache/kvrocks/blob/2.9/LICENSE
  summary: Apache Kvrocks is a distributed key value NoSQL database that uses RocksDB as storage engine and is compatible with Redis protocol

extra:
  recipe-maintainers:
    - mguijarr
